name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r ./docker/requirements.txt
          pip install pylint --upgrade
          pip install pylint-flask
          pip install pylint_flask_sqlalchemy
      - name: Run Pylint
        run: |
          cd api
          pylint --load-plugins pylint_flask_sqlalchemy app
  
  Unittest:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r ./docker/requirements.txt
      - name: Run unit tests
        run: |
          cd api
          python -m unittest discover -s tests/unit/ 

  IntegrationTest:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Spin up containers
        env:
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          PYLINTHOME: ${{ secrets.PYLINTHOME }}
        run: docker-compose -f docker-compose.ci.yml up -d
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '15s'
      - name: Check running containers
        run: docker ps -a
      - name: Run integration tests
        run: docker-compose -f docker-compose.ci.yml exec -T api python -m unittest discover -s tests/integration/