name: Pylint

on:
  pull_request:
    branches: [ master ]

jobs:
  Pylint:
      runs-on: ubuntu-latest
      steps:
        - name: Python Pylin GitHub Action
          uses: fylein/python-pylint-github-action@v1
          with:
            args: pip3 install -r requirements.txt && pylint --rcfile=.pylintrc app
        

      